image: alpine:latest

pages:
  stage: deploy
  tags:
    - ubuntu_DOCKER
  script:
    - cp -r docs .public
    - mv .public public
    - ls -la public
  artifacts:
    paths:
      - public
  only:
    - master
