image: alpine:latest

pages:
  stage: deploy
  tags:
    - ubuntu_DOCKER
  script:
    - mkdir .public
    - cp -r docs/ .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
